name: Run Tests and ESLint in a React Native App
on:
  push:
    branches:
      - "main"

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install
        run: |
          npm install

      - name: Run ESLint
        run: npm run eslint