name: Run Tests and ESLint in a React Native App
on:
  push:
    branches:
      - "main"

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Lint files
        run: npm run eslint